- name: "Set modified vars"
  set_fact:
    ad_group_sudo_file: "{{ ad_group.name | replace(' ', '_') }}"
    sudoers_template: '%{{ ad_group.name | replace(" ", "\ ")}} ALL=(ALL) ALL'
    sudo_access: "{{ad_group.sudo_access | default('false')}}"

- name: "Use Custom Sudo Template"
  set_fact:
    sudoers_template: "{{ad_group.sudoers_template}}"
  when: "'sudoers_template' in ad_group"

- name: Check if {{ ad_group.name }} group can login through ssh
  command: /bin/bash -c "/usr/sbin/realm list | grep '{{ ad_group.name }}'"
  register: group_can_login
  changed_when: false
  ignore_errors: true

- name: Permit {{ ad_group.name }} group login
  command: /bin/bash -c "/usr/sbin/realm permit -g '{{ ad_group.name }}'" 
  when: group_can_login|failed
- name: Add {{ ad_group.name }} group to sudoers
  lineinfile: 
    line="{{sudoers_template}}"
    path="/etc/sudoers.d/{{ ad_group_sudo_file }}" 
    owner=root 
    group=root 
    mode=044 
    create=true
  when: sudo_access 
